version: '3.8'

services:
    web:
      build: .
      command: python3 /code/manage.py runserver 0.0.0.0:8000
      volumes:
       - .:/code
      ports:
       - "8000:8000"
      depends_on:
       - db
      environment:
       - debug=docker_django_debug
       - DJANGO_SECRET_KEY=docker_django_secret_key
       - django_db=docker_django_db
       - django_db_user=docker_django_db_user
       - django_db_password=docker_django_db_password

    db:
      image: postgres:14
      environment:
      - POSTGRES_HOST_AUTH_METHOD=trust


